---
title: "Proyecto Contigencias de Vida II - CA0309"
oauthor: 
- Ashley Arrieta Padilla | C00753
- Henri Gerard Gabert Hidalgo | B93096
- Juan Pablo Morgan Sandí | C15319
- Erick Venegas Espinoza | C09319

date: "`r Sys.Date()`"
output: 
  html_document:
    theme: flatly
    toc: yes
    toc_float:
      collapsed: true
  extra_dependencies: ['amsmath', 'someotherpackage']
---

```{r}
source("code/setup.R")
```

```{r}
tpxM(59, 2, 0, 0, lista_tablas_masc)
```
```{r}
anualidad_discreta(48, 4, 0, 2, 0.03, "M")
```

```{r}
anualidad_discreta(48, 4, 0, 1, 0.03, "M")
```
```{r}
anualidad_discreta(48, 4, 0, 0, 0.03, "M")
```

```{r}
anualidad_discreta_post(60, 3, 0, 0, 0.03, "M")
```

```{r}
seguro(66, 4, 1, 3, 0.03, "M")
```


```{r}
prima(20, 0.03, "M")
```

```{r}
primas <-0
for(k in seq(20, 64, 1)){
  primas[k-19] <- prima(k, 0.03, "M")
}
```
```{r}
prima_nivelada <- mean(primas)
prima_nivelada
```
```{r}
seguro_permanencia(68, 5, 0, 3, 0.03, "M")
```

```{r}
tpxM_permanencia(70, 8, 0, 1, lista_tablas_masc)
```

